### ISSUE TITLE
Project Update 10-08

### ISSUE THREAD

**Issue by naiyaodhner** [EmilyMartin42/Shakespearean_Insults#2]
This week we solidified our decisions on what source we will pull our base-XMLs from, what plays we will be marking-up, and who will be responsible for mark-up of each document. As our group has to incorporate some linguistic features into our project, we figured that the easiest way to divide our responsibilities is to have our group members who aren’t familiar with linguistics do an initial phase primarily consisting of mark-up focusing on finding all of the insults in our works, and our other members will be doing linguistics-focused mark-up once that first phase is complete. For phase-1 mark-up, we are currently thinking of having Dillon do the comedies and Mason do the tragedies. We discussed in our meeting that this may create an unevenness in our work in the sense that each member is only working on one type of play (since some of out preliminary research questions hinge on our ability to compare the insults in comedies vs. in tragedies evenly), however we also thought that this may have advantages because it could mean that by the second play they are familiar with how to find the insults that it contains a bit more easily.. We are also currently looking for things for Emily and I to do in the meantime so that the workload is fair for everyone, and in order to make sure that we stay on track. Currently we are thinking to work on the basics for our schema and website layout.

We also did some planning for next week in our meeting, and our goals are as follows:
1. have formulated a set of “steps” for marking-up insults (Dillon and Mason)
2. push our XML files to our github repo (Emily)
3. have met with/have a date and time to meet with Narae Han to check-in about our linguistics-focused research questions (Naiya)
-no

**Comment by cmarkulin** [comment]
I feel like there shouldn't be an issue having only one type of play be covered by each person, as long as your group has a well defined method of choosing the insults and analyzing them. I also feel like it would be more beneficial than detrimental since the differences in mark up may make it easier to find differences in the insults in tragedies vs. comedies.
