### ISSUE TITLE
Project Update

### ISSUE THREAD

**Issue by EmilyMartin42** [EmilyMartin42/Shakespearean_Insults#5]
For this week: Dillon and Mason have finished marking up all the plays for insults, Emily and Naiya have begun working on marking up the insults linguistically and the website has been started. 

This week: In this weeks project meeting we cleared up a few areas of ambiguity in our linguistic markup for the plays by refining our tags for character relationships as well as including a tag for when a character insults themselves. The issue of flirtatious insults will have to be revisited after we work more on a Midsummer Nights Dream. We went over our goals for next week and made sure we were on track for the midterm deadline. 

For next week: Both the markdown document and the schema will be updated with the new linguistic markup information and Naiya and Emily will finish the linguistic markup of the plays by our next meeting on Wednesday. In that time we will also keep working on our project website.

**Comment by cdornn** [comment]
Looks like you guys are on a pretty solid path here! I read Midsummer Nights Dream in high school (which I loved), so I find it so neat that you will be marking up the flirtatious insults that are in it, as there certainly is a great deal. Looks like you guys are going to be reaching the project deadline no problem and have done a great deal of strong work so far, so keep that up and I can't wait to see how it turns out!

**Comment by ShaneMoniot** [comment]
It seems like this project is really moving along nicely. My team (Federalist Papers) also had to refine some of our tags, and I think it really helped us a lot. Like the comment above me says, it doesn't seem like you guys will have any trouble reaching your midterm goals. I am excited to see the final results!

**Comment by Zeoastua** [comment]
It's good to see a lighter load of what needs to get done; I can only imagine the stress of everything from the last update. My team also refined our markup strategies, and it's nice to see that we were not the only group whose markup wasn't to a perfect schema the first time around. I'm excited to see what comes next!

**Comment by akc472** [comment]
Good luck on fixing the issue for flirtatious insults! It's interesting to see all ways the texts differentiate once you start analyzing them, especially texts like Shakespeare. That's kind of what my team encountered these past few weeks too when we tried to categorize the moods and tones for song lyrics. It's always good to be more specific than ambiguous!

**Comment by cmarkulin** [comment]
This project seems to be going along nicely. I like that you guys already started on the HTML and the site's layout looks pretty good right now. I think that navbar looks good and with a little bit more CSS for paragraph elements and headers, I think the site should look complete (minus the actual data of course).
