### ISSUE TITLE
Project Update 11-05

### ISSUE THREAD

**Issue by naiyaodhner** [EmilyMartin42/Shakespearean_Insults#6]
For this week: Dillon and Mason have been working on website design, and have nearly finalized the base layout for most pages (other than the corpus.) Naiya and Emily have completed the linguistic markup of our xmls [as stated in the “This week” section, we will be adding new changes].

This week: In our meeting this week we revisited midterm goals to ensure that everything is on track, and slightly adjusted our goals as the initial goal to transform our documents with XSLT before Monday did not appear to be realistic. We discussed options for our website’s corpus page, as we need to finalize it very soon. There was no clear conclusion, but the ideas that were generated will be tested soon in order to see if they are workable - currently we are slightly stuck on how to display our options in toggle-selection menu boxes while fitting everything on one page, because we do not want users to have to scroll through all of our results (we are thinking to have the results appear in a scrollable box, as opposed to the page itself being scrollable.) We also reviewed some insults that come up in our linguistic markup that prompted us to adjust our tags in order to include rel=”couple-couple” for couples and rel=”acq-acq” for acquaintances, so we will be adjusting our xmls in order to incorporate those. We also noticed a drastic difference between the number of insults in Hamlet and all of our other plays, so Emily agreed to go through Hamlet in order to ensure that our count of insults for it is accurate. Besides that, we discussed how to use schematron to ensure that our markup is correct (in both spelling and order).

For next week: We will primarily be working to complete our midterm goals this week, so we intend to finalize our schema and methodology write-up, and to come to a decision on how to arrange the corpus page.

**Comment by Zeoastua** [comment]
It seems like the project is on the precipice of being super fruitful in its next steps! It sounds as if on the next update, the workings of a baby-site will be fully up and running, and you'll be able to display _something_ to at least yourselves. I'm intrigued as to the insult count in Hamlet; why does Hamlet, of all plays, carry such a high number? I'm excited to see more!

**Comment by darianmcginnis** [comment]
Wow you guys really have everything planned. I like the goals and I like the fact that you guys were able to understand your limits on what you were able to do by midterm time! It’s actually kind of cool that Hamlet has the most insults. I’m really excited to see why since thats what we’ve been focusing on in class and I actually read that one a few years ago. I think what you guys have going on is awesome!

**Comment by victoriacosta** [comment]
I think your project is really coming along by the sounds of this update. I really like your initial design for your site. It really suits your topic. I think it was a wise decision to reevaluate your XSLT goals and set it aside for now. I think when we do projects like these its important to manage our expectations when it comes to tasks holistically and know when you need to walk away from something, even just temporarily. I can't wait to see more!
